[project]
name = "{{ cookiecutter.package_name }}"
authors = [
    {name = "Adam Pirog"},
    {email = "pirog.adam@gmail.com"},
]
description = "{{ cookiecutter.short_project_description }}"
readme = "README.md"
license = {text="MIT"}
license-files = ["LICENSE"]
dynamic = ["version"]
requires-python = ">=3.13"
dependencies = [

    ]

[project.optional-dependencies]
dev = [
    "ruff",
    "pytest"
    ]

[build-system]
requires = ["setuptools>=77"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
include = ["{{ cookiecutter.package_name }}*"]

[tool.setuptools.dynamic]
version = {attr = "{{ cookiecutter.package_name }}.version.__version__"}

{%- if cookiecutter.command_line_interface == "y" %}
[project.scripts]
{{ cookiecutter.package_slug }} = "{{ cookiecutter.package_name }}.__main__:cli"
{%- endif %}

[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-ra"
testpaths = ["tests"]

[tool.ruff]
line-length = 100
target-version = "py313"

[tool.ruff.lint]
extend-select = [
    "E",    # pycodestyle errors
    "W",    # pycodestyle warnings
    "F",    # pyflakes
    "I",    # isort
    "B",    # flake8-bugbear
    "A",    # flake8-builtins
    "N",    # pep8-naming
    "C90",  # mccabe complexity
    "UP",   # pyupgrade
    "C4",   # flake8-comprehensions
    "RUF",  # ruff-specific rules
]

[tool.ruff.lint.mccabe]
max-complexity = 10

[tool.ruff.lint.isort]
lines-after-imports = 2