[build-system]
requires = ["setuptools>=42.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[tool.black]
line-length = 79
target-version = ["py38"]

[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-ra"
testpaths = ["tests"]

[tool.isort]
profile = "black"
line_length = 79
lines_after_imports = 2

[tool.flake8]
extend-ignore = [
    "E203",  # whitespace before ':' (black)
]
per-file-ignores = [
    "*/__init__.py:F401",  # imported but unused
]
max-complexity = 10
max-line-length = 79
exclude = [".git", ".eggs" ,"build", "dist"]
